# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"9\n\x0e\x43\x61talogRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"\x89\x01\n\x0b\x43\x61talogItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x05\x12\x15\n\rprice_dollars\x18\x06 \x01(\t\x12\x13\n\x0bprice_cents\x18\x07 \x01(\t\".\n\x0f\x43\x61talogResponse\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.CatalogItem27\n\x07\x43\x61talog\x12,\n\x07\x43\x61talog\x12\x0f.CatalogRequest\x1a\x10.CatalogResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATALOGREQUEST._serialized_start=17
  _CATALOGREQUEST._serialized_end=74
  _CATALOGITEM._serialized_start=77
  _CATALOGITEM._serialized_end=214
  _CATALOGRESPONSE._serialized_start=216
  _CATALOGRESPONSE._serialized_end=262
  _CATALOG._serialized_start=264
  _CATALOG._serialized_end=319
# @@protoc_insertion_point(module_scope)
